project:
  title: "US-China Replication "
  type: datapage

website:
  navbar:
    logo: images/logo.png

format:
  datapage-html:
    theme: theme.scss

execute: 
  echo: false
  message: false
  warning: false
  error: false

redivis:
  user: anjiecao
  dataset: us_china_comparison
  table: study_1
