project:
  title: "US-China differences in cognition and perception across 12 tasks: Replicability, robustness, and within-culture variation"
  type: datapage

website:
  navbar:
    logo: images/logo.png

format:
  datapage-html:
    theme: theme.scss

execute: 
  echo: false
  message: false
  warning: false
  error: false

redivis:
  user: datapages
  dataset: palmerpenguins
  table: penguins
